// "use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// custom import
import Navbar from "@/components/navbar_custom";
import Image from "next/image";
import { label } from "framer-motion/client";
import AdminButton from '@/components/adminButton'; // Import the AdminButton component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const navLinks = [
  {label: "Home", href: "/"},
  { label: "ท่อ", href: "/pipe" },
  { label: "ปูนผง", href: "/cement" },
  { label: "คอนกรีตผสมเสร็จ", href: "/concrete" },
  { label: "เหล็กเส้น", href: "/metal" },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="">
         <Navbar links={navLinks}>
         <AdminButton />
         </Navbar>
              {/* Hero Section with Fixed Background */}
              <div className="relative w-full h-[50vh] overflow-hidden">
                <Image
                  src="/building_home.png" // Replace with your image path
                  alt="Hero Background"
                  layout="fill"
                  objectFit="cover"
                //   className="absolute top-0 left-0 w-full h-full z-0"
                />
              </div>
          </div>
          {/* Text Overlay */}
      <div className="absolute top-0 left-0 w-full h-[60vh] flex items-center justify-center z-10">
          {/* absolute: positions the div absolutely in relation to its parent */}
          {/* top-0 left-0: positions the text overlay at the top-left */}
          {/* w-full h-full: makes the overlay cover the full hero area */}
          {/* flex: uses flexbox to center the text */}
          {/* items-center: vertically centers the text */}
          {/* justify-center: horizontally centers the text */}
          {/* z-10: ensures the text is above the hero image */}

          <p className="text-white text-6xl italic">{/* text-white: makes text white */}
            Lohakit Udon
          </p>
        </div>
        {/* <div className="mt-16"> Push content down to avoid overlap */}
        <div className="relative min-h-screen">
          <main className="relative z-10 flex flex-col justify-center items-center pt-[2vh] bg-white w-full">
            {children}
          </main>
        </div>
        <footer className="p-4 text-center border-t">
        © {new Date().getFullYear()} My Website. All rights reserved.
      </footer>
        {/* </div> */}
      </body>
    </html>
  );
}
